name: display two messages
on:
  push:
    branches: 
      - main
jobs:
  display-2-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: display-variable
        run: | 
          echo "my variable is:$VARIABLE and secret password is ${{ PASS }}"
        env: 
          VARIABLE: '12345'
          PASS: ${{ secrets.PASSWORD }}
